version: 2
registries:
  composer-repository-packages-itineris-co-uk-herokuapp-com:
    type: composer-repository
    url: https://packages-itineris-co-uk.herokuapp.com
    username: dependabot
    password: "${{secrets.COMPOSER_REPOSITORY_PACKAGES_ITINERIS_CO_UK_HEROKUAPP_COM_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/London
  ignore:
  - dependency-name: psr/container
    versions:
    - 1.1.1
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.72
    - 0.12.82
  - dependency-name: symfony/yaml
    versions:
    - 4.4.20
  registries:
  - composer-repository-packages-itineris-co-uk-herokuapp-com
