version: 1

update_configs:
  - package_manager: php:composer
    directory: /
    update_schedule: live
    allowed_updates:
      - match:
          update_type: all
    automerged_updates:
      - match:
          update_type: all
